// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/benhammondmusic/my-denver-card-free/internal/models"
	"strings"
)

func freeMonthsLabel(v models.Venue) string {
	if len(v.FreeMonths) == 12 {
		return "Year-round"
	}
	return strings.Join(v.FreeMonths, ", ")
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func Index(venues []models.Venue) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"hero-section\"><p class=\"hero-eyebrow\">Free today</p><div id=\"free-now-chips\" class=\"venue-chips\"></div><div id=\"hero-soon\"><div class=\"hero-divider\"></div><p class=\"hero-eyebrow soon\">Free next month</p><div id=\"free-soon-chips\" class=\"venue-chips\"></div></div></div><p class=\"browse-label\">Browse all venues</p><div class=\"filter-bar\"><div class=\"filter-tabs\"><button class=\"filter-tab\" data-filter=\"all\">All</button> <button class=\"filter-tab\" data-filter=\"now\">Free Now</button> <button class=\"filter-tab\" data-filter=\"weekend\">This Weekend</button> <button class=\"filter-tab\" data-filter=\"summer\">Summer</button> <button class=\"filter-tab\" data-filter=\"yearround\">Year-Round</button></div><div class=\"toolbar\"><button class=\"toolbar-btn\" id=\"near-me-btn\" title=\"Sort venues by distance from your location\">Near me</button> <button class=\"toolbar-btn\" id=\"map-toggle-btn\">Show map</button> <select id=\"kid-age\" class=\"age-select\" aria-label=\"Filter by age\"><option value=\"0\">All ages</option> <option value=\"4\">Has a toddler (under 5)</option> <option value=\"8\">School age (5-12)</option> <option value=\"15\">Teen (13+)</option></select></div></div><div id=\"map-panel\" class=\"map-panel\"></div><p class=\"venue-count\"></p><ul class=\"venue-list\" id=\"venue-list\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, v := range venues {
				if v.Featured && !v.TemporarilyClosed {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li class=\"section-divider\" aria-hidden=\"true\"><span>More venues</span></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, v := range venues {
				if !v.Featured && !v.TemporarilyClosed && v.Lat != 0 {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"section-divider\" aria-hidden=\"true\"><span>City recreation</span></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, v := range venues {
				if !v.Featured && !v.TemporarilyClosed && v.Lat == 0 {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			for _, v := range venues {
				if v.TemporarilyClosed {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ul><div id=\"modal-overlay\" class=\"modal-overlay\" aria-hidden=\"true\"><div class=\"modal-sheet\"><div class=\"modal-band\" id=\"modal-band\"></div><div class=\"modal-content\"><div class=\"modal-header\"><h2 class=\"modal-title\" id=\"modal-title\"></h2><button class=\"modal-close\" id=\"modal-close\" aria-label=\"Close\"><svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" aria-hidden=\"true\"><line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"></line> <line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"></line></svg></button></div><div class=\"modal-badges\" id=\"modal-badges\"></div><div id=\"modal-map\" class=\"modal-map\"></div><div class=\"modal-details\" id=\"modal-details\"></div><div class=\"modal-actions\" id=\"modal-actions\"></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = filterScript().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("My Denver Card Free: Denver Cultural Venues").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func VenueRow(v models.Venue) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var4 = []any{"venue-row", templ.KV("venue-featured", v.Featured), templ.KV("program-general", v.Program == models.ProgramGeneral), templ.KV("venue-closed", v.TemporarilyClosed)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<li role=\"button\" tabindex=\"0\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var4).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" data-free-months=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(strings.Join(v.FreeMonths, ","))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 109, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-schedule=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(string(v.FreeSchedule))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 110, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" data-closed=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.TemporarilyClosed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 111, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" data-program=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(string(v.Program))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 112, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" data-lat=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%.6f", v.Lat))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 113, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" data-lng=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%.6f", v.Lng))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 114, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" data-address=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.Address)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 115, Col: 26}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" data-indoor=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.Indoor))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 116, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" data-reservation=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.ReservationRequired))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 117, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" data-min-age=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", v.MinAge))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 118, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" data-max-age=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", v.MaxAge))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 119, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\" data-name=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 120, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" data-url=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.URL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 121, Col: 18}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\" data-notes=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.Notes)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 122, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var19)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" data-closure-reason=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.ClosureReason)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 123, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\" data-hours=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var21 string
		templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.Hours)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 124, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var21)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\" data-adults=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 string
		templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", v.AdultsIncluded))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 125, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var22)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "\" data-scrape-failed=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.ScrapeFailed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 126, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var23)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "\" data-scrape-error=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var24 string
		templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.ScrapeError)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 127, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var24)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\"><div class=\"venue-band\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "<span class=\"band-label\">Closed</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if v.Program == models.ProgramGeneral {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<span class=\"band-label\">Free</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<span class=\"band-label\">Card</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</div><div class=\"venue-body\"><p class=\"venue-name\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var25 string
		templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(v.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 139, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</p></div><div class=\"venue-status\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "<span class=\"badge badge-red\">closed</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			switch {
			case v.AdultsIncluded >= 2:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "<span class=\"badge badge-green\">Whole family</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case v.AdultsIncluded == 1:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "<span class=\"badge badge-green\">+1 adult</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			default:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "<span class=\"badge badge-yellow\">Kids free</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, " <span class=\"months\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var26 string
			templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.JoinStringErrs(freeMonthsLabel(v))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 153, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var26))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</div></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func filterScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var27 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var27 == nil {
			templ_7745c5c3_Var27 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(`<script>
(function () {
  // === DATE / SCHEDULE CONSTANTS ===
  var MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  var today = new Date();
  var currentMonthName = MONTHS[today.getMonth()];
  var nextMonthName = MONTHS[(today.getMonth() + 1) % 12];
  var dow = today.getDay(); // 0=Sun 6=Sat
  var isWeekend = dow === 0 || dow === 5 || dow === 6; // Fri Sat Sun

  var weekendDates = (function () {
    var daysToFri = dow === 0 ? -2 : dow === 6 ? -1 : 5 - dow;
    return [0, 1, 2].map(function (i) {
      var d = new Date(today);
      d.setDate(today.getDate() + daysToFri + i);
      return d;
    });
  })();

  // School break approximation; update annually for DPS calendar
  function isSchoolBreak(d) {
    var m = d.getMonth(), day = d.getDate();
    if ((m === 11 && day >= 20) || (m === 0 && day <= 5)) return true; // Winter
    if (m === 2 && day >= 15 && day <= 29) return true;                 // Spring
    if (m >= 5 && m <= 7) return true;                                   // Summer Jun-Aug
    return false;
  }
  var inBreak = isSchoolBreak(today);

  // === STATE ===
  var activeFilter = 'now';
  var kidAge = 0;
  var userLat = null, userLng = null;
  var mapInitialized = false;
  var leafletMap = null;
  var modalMap = null;

  // === DOM REFS ===
  var rows = Array.prototype.slice.call(document.querySelectorAll('.venue-row'));
  var tabs = document.querySelectorAll('.filter-tab');
  var countEl = document.querySelector('.venue-count');
  var modalOverlay = document.getElementById('modal-overlay');
  var modalBand = document.getElementById('modal-band');
  var modalTitle = document.getElementById('modal-title');
  var modalBadges = document.getElementById('modal-badges');
  var modalMapEl = document.getElementById('modal-map');
  var modalDetails = document.getElementById('modal-details');
  var modalActions = document.getElementById('modal-actions');

  // === VENUE HELPERS ===
  function freeMonths(row) {
    return (row.dataset.freeMonths || '').split(',').filter(Boolean);
  }

  function freeNow(row) {
    if (row.dataset.closed === 'true') return false;
    if (freeMonths(row).indexOf(currentMonthName) === -1) return false;
    var sched = row.dataset.schedule || 'daily';
    if (sched === 'weekends') return isWeekend;
    if (sched === 'weekends_and_breaks') return isWeekend || inBreak;
    return true;
  }

  function freeThisWeekend(row) {
    if (row.dataset.closed === 'true') return false;
    var sched = row.dataset.schedule || 'daily';
    return weekendDates.some(function (d) {
      var monthName = MONTHS[d.getMonth()];
      if (freeMonths(row).indexOf(monthName) === -1) return false;
      return true;
    });
  }

  function freeInMonth(row, m) {
    return row.dataset.closed !== 'true' && freeMonths(row).indexOf(m) !== -1;
  }

  function isSummer(row) {
    if (row.dataset.closed === 'true') return false;
    var fm = freeMonths(row);
    return fm.indexOf('June') !== -1 || fm.indexOf('July') !== -1 || fm.indexOf('August') !== -1;
  }

  function isYearRound(row) {
    return row.dataset.closed !== 'true' && freeMonths(row).length === 12;
  }

  function passesAgeFilter(row) {
    if (kidAge === 0) return true;
    var minAge = parseInt(row.dataset.minAge || '0', 10);
    var maxAge = parseInt(row.dataset.maxAge || '0', 10);
    if (minAge > 0 && kidAge < minAge) return false;
    if (maxAge > 0 && kidAge > maxAge) return false;
    return true;
  }

  // === DISTANCE (Haversine, miles) ===
  function haversine(lat1, lng1, lat2, lng2) {
    var R = 3958.8;
    var dLat = (lat2 - lat1) * Math.PI / 180;
    var dLng = (lng2 - lng1) * Math.PI / 180;
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
            Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
            Math.sin(dLng/2) * Math.sin(dLng/2);
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  // === FILTER ===
  function _doApplyFilter() {
    var visible = 0;
    rows.forEach(function (row) {
      var closed = row.dataset.closed === 'true';
      var ageOk = closed || passesAgeFilter(row);
      var show;
      switch (activeFilter) {
        case 'now':       show = closed || (freeNow(row) && ageOk);         break;
        case 'weekend':   show = closed || (freeThisWeekend(row) && ageOk); break;
        case 'summer':    show = closed || (isSummer(row) && ageOk);        break;
        case 'yearround': show = closed || (isYearRound(row) && ageOk);     break;
        default:          show = closed || ageOk;
      }
      row.classList.toggle('hidden', !show);
      if (show && !closed) visible++;
    });

    var label = visible + (visible === 1 ? ' venue' : ' venues');
    if (activeFilter === 'now') {
      label += ' free today';
      if (visible === 0) label = 'No venues free right now. Try "All" or pick a filter.';
    } else if (activeFilter === 'weekend') {
      label += ' free this weekend';
      if (visible === 0) label = 'Nothing free this weekend. Try "All".';
    }
    var AGE_LABELS = { '4': 'under 5', '8': 'ages 5-12', '15': 'teens 13+' };
    if (kidAge > 0) label += ' (' + (AGE_LABELS[String(kidAge)] || 'age ' + kidAge) + ')';
    if (countEl) countEl.textContent = label;
  }

  function applyFilter() {
    if (document.startViewTransition) {
      document.startViewTransition(_doApplyFilter);
    } else {
      _doApplyFilter();
    }
  }

  // === HERO ===
  function buildHero() {
    var nowChips = document.getElementById('free-now-chips');
    var soonChips = document.getElementById('free-soon-chips');
    var heroSoon = document.getElementById('hero-soon');
    var soonLabel = document.querySelector('.hero-eyebrow.soon');
    if (!nowChips || !soonChips) return;

    if (soonLabel) soonLabel.textContent = 'Coming up in ' + nextMonthName;

    var nowRows = rows.filter(function (row) { return freeNow(row); });
    var soonRows = rows.filter(function (row) {
      return !freeNow(row) && freeInMonth(row, nextMonthName) && row.dataset.closed !== 'true';
    });

    function makeChip(row, isSoon) {
      var btn = document.createElement('button');
      var cls = 'venue-chip';
      if (row.dataset.program === 'general') cls += ' general';
      if (isSoon) cls += ' chip-soon';
      btn.className = cls;
      btn.textContent = row.dataset.name || '';
      btn.addEventListener('click', function () { openModal(row); });
      return btn;
    }

    if (nowRows.length === 0) {
      var empty = document.createElement('span');
      empty.className = 'chip-empty';
      empty.textContent = 'Nothing is free right now. Try "All" to browse.';
      nowChips.appendChild(empty);
    } else {
      nowRows.forEach(function (row) { nowChips.appendChild(makeChip(row, false)); });
    }

    if (soonRows.length === 0) {
      if (heroSoon) heroSoon.style.display = 'none';
    } else {
      soonRows.forEach(function (row) { soonChips.appendChild(makeChip(row, true)); });
    }
  }

  // === FULL MAP ===
  function initMap() {
    if (mapInitialized || typeof L === 'undefined') return;
    mapInitialized = true;

    leafletMap = L.map('map-panel').setView([39.7392, -104.9849], 12);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      maxZoom: 19
    }).addTo(leafletMap);

    rows.forEach(function (row) {
      var lat = parseFloat(row.dataset.lat || '0');
      var lng = parseFloat(row.dataset.lng || '0');
      if (!lat || !lng) return;

      var name = row.dataset.name || '';
      var isFreeNow = freeNow(row);
      var isClosed = row.dataset.closed === 'true';
      var isGeneral = row.dataset.program === 'general';
      var color = isClosed ? '#6b7280' : (isFreeNow ? (isGeneral ? '#d97706' : '#002868') : '#93c5fd');

      var marker = L.circleMarker([lat, lng], {
        radius: 10,
        fillColor: color,
        color: 'white',
        weight: 2,
        fillOpacity: 0.88
      });

      var statusHtml = isClosed
        ? '<span style="color:#991b1b">Temporarily closed</span>'
        : (isFreeNow
          ? '<span style="color:#065f46;font-weight:700">Free today</span>'
          : '<span style="color:#6b7280">Not free this month</span>');
      var popupHtml = '<div style="min-width:130px"><strong>' + name + '</strong><br>' + statusHtml + '<br><button class="map-popup-btn">View details</button></div>';
      marker.bindPopup(popupHtml, { maxWidth: 220 });
      marker.on('popupopen', (function (r, m) {
        return function (e) {
          var btn = e.popup.getElement().querySelector('.map-popup-btn');
          if (btn) btn.onclick = function () { m.closePopup(); openModal(r); };
        };
      })(row, marker));
      marker.addTo(leafletMap);
    });

    if (userLat && userLng) addUserMarker();
    setTimeout(function () { if (leafletMap) leafletMap.invalidateSize(); }, 100);
  }

  function toggleMap() {
    var panel = document.getElementById('map-panel');
    var btn = document.getElementById('map-toggle-btn');
    if (!panel) return;
    var isVisible = panel.classList.contains('visible');
    panel.classList.toggle('visible', !isVisible);
    if (btn) { btn.textContent = isVisible ? 'Show map' : 'Hide map'; btn.classList.toggle('active', !isVisible); }
    if (!isVisible) {
      initMap();
      setTimeout(function () { if (leafletMap) leafletMap.invalidateSize(); }, 150);
    }
  }

  function addUserMarker() {
    if (!leafletMap || !userLat || !userLng) return;
    L.circleMarker([userLat, userLng], {
      radius: 8,
      fillColor: '#bf0a30',
      color: 'white',
      weight: 2,
      fillOpacity: 0.9
    }).bindPopup('You are here').addTo(leafletMap);
    leafletMap.setView([userLat, userLng], 13);
  }

  // === MODAL HELPERS ===
  function slugify(str) {
    return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  }

  function addBadge(container, text, cls, title) {
    var span = document.createElement('span');
    span.className = 'badge ' + cls;
    span.textContent = text;
    if (title) span.title = title;
    container.appendChild(span);
  }

  function initModalMap(lat, lng, name, color) {
    if (typeof L === 'undefined') return;
    if (modalMap) { modalMap.remove(); modalMap = null; }
    setTimeout(function () {
      modalMap = L.map('modal-map', { zoomControl: true, scrollWheelZoom: false }).setView([lat, lng], 15);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        maxZoom: 19
      }).addTo(modalMap);
      L.circleMarker([lat, lng], {
        radius: 10,
        fillColor: color,
        color: 'white',
        weight: 2,
        fillOpacity: 0.9
      }).bindPopup(name).addTo(modalMap);
      modalMap.invalidateSize();
    }, 150);
  }

  // === MODAL ===
  function openModal(row, skipHistory) {
    if (!modalOverlay) return;

    var name = row.dataset.name || '';
    var url = row.dataset.url || '';
    var notes = row.dataset.notes || '';
    var closureReason = row.dataset.closureReason || '';
    var hours = row.dataset.hours || '';
    var adults = parseInt(row.dataset.adults || '0', 10);
    var schedule = row.dataset.schedule || 'daily';
    var months = (row.dataset.freeMonths || '').split(',').filter(Boolean);
    var closed = row.dataset.closed === 'true';
    var indoor = row.dataset.indoor === 'true';
    var reservation = row.dataset.reservation === 'true';
    var scrapeFailed = row.dataset.scrapeFailed === 'true';
    var scrapeError = row.dataset.scrapeError || '';
    var lat = parseFloat(row.dataset.lat || '0');
    var lng = parseFloat(row.dataset.lng || '0');
    var program = row.dataset.program || 'mydenvercard';
    var isFreeNow = freeNow(row);

    var bandColor = closed ? '#6b7280' : (program === 'general' ? '#d97706' : '#002868');
    if (modalBand) modalBand.style.background = bandColor;
    if (modalTitle) modalTitle.textContent = name;

    if (modalBadges) {
      modalBadges.innerHTML = '';
      if (closed) {
        addBadge(modalBadges, 'temporarily closed', 'badge-red');
      } else {
        if (isFreeNow) addBadge(modalBadges, 'free today', 'badge-green');
        if (adults >= 2) addBadge(modalBadges, 'whole family free', 'badge-green');
        else if (adults === 1) addBadge(modalBadges, 'free +1 adult', 'badge-green');
        else addBadge(modalBadges, 'kids free', 'badge-yellow');
        if (schedule === 'weekends') addBadge(modalBadges, 'weekends only', 'badge-gray');
        else if (schedule === 'weekends_and_breaks') addBadge(modalBadges, 'weekends + breaks', 'badge-gray');
        if (reservation) addBadge(modalBadges, 'reservation required', 'badge-yellow');
        if (indoor) addBadge(modalBadges, 'indoor', 'badge-gray');
        if (scrapeFailed) addBadge(modalBadges, 'data outdated', 'badge-red', scrapeError);
      }
    }

    if (modalDetails) {
      modalDetails.innerHTML = '';
      var detailText = closed ? closureReason : notes;
      if (detailText) {
        var p = document.createElement('p');
        p.className = 'modal-notes';
        p.textContent = detailText;
        modalDetails.appendChild(p);
      }
      if (hours) {
        var h = document.createElement('p');
        h.className = 'modal-hours';
        h.innerHTML = '<strong>Hours:</strong> ' + hours;
        modalDetails.appendChild(h);
      }
      if (!closed && months.length > 0) {
        var m = document.createElement('p');
        m.className = 'modal-months';
        var monthsLabel = months.length === 12 ? 'Year-round' : months.join(', ');
        m.innerHTML = '<strong>Free in:</strong> ' + monthsLabel;
        modalDetails.appendChild(m);
      }
    }

    if (modalActions) {
      modalActions.innerHTML = '';
      if (url) {
        var link = document.createElement('a');
        link.href = url;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.className = 'modal-action-btn';
        link.textContent = 'Visit website';
        modalActions.appendChild(link);
      }
      if (row.dataset.address) {
        var dirBtn = document.createElement('button');
        dirBtn.className = 'modal-action-btn';
        dirBtn.textContent = 'Directions';
        dirBtn.addEventListener('click', function () { getDirections(row); });
        modalActions.appendChild(dirBtn);
      }
      var shareBtn = document.createElement('button');
      shareBtn.className = 'modal-action-btn';
      shareBtn.textContent = 'Share';
      shareBtn.addEventListener('click', function () { shareVenue(shareBtn, name); });
      modalActions.appendChild(shareBtn);
    }

    if (lat && lng) {
      if (modalMapEl) modalMapEl.style.display = 'block';
      initModalMap(lat, lng, name, bandColor);
    } else {
      if (modalMapEl) modalMapEl.style.display = 'none';
      if (modalMap) { modalMap.remove(); modalMap = null; }
    }

    modalOverlay.setAttribute('aria-hidden', 'false');
    modalOverlay.classList.add('open');
    document.body.style.overflow = 'hidden';

    if (!skipHistory) history.pushState({ modal: slugify(name) }, '', '#' + slugify(name));

    var closeBtn = document.getElementById('modal-close');
    if (closeBtn) setTimeout(function () { closeBtn.focus(); }, 50);
  }

  function closeModal(skipHistory) {
    if (!modalOverlay) return;
    modalOverlay.setAttribute('aria-hidden', 'true');
    modalOverlay.classList.remove('open');
    document.body.style.overflow = '';
    if (!skipHistory) history.pushState(null, '', window.location.pathname + window.location.search);
    if (modalMap) { modalMap.remove(); modalMap = null; }
  }

  if (modalOverlay) {
    modalOverlay.addEventListener('click', function (e) {
      if (e.target === modalOverlay) closeModal();
    });
  }
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && modalOverlay && modalOverlay.classList.contains('open')) closeModal();
  });
  var modalCloseBtn = document.getElementById('modal-close');
  if (modalCloseBtn) modalCloseBtn.addEventListener('click', function () { closeModal(); });
  window.addEventListener('popstate', function () {
    if (modalOverlay && modalOverlay.classList.contains('open')) closeModal(true);
  });

  // === GEOLOCATION / NEAR ME ===
  function hasBoth(row) {
    var lat = parseFloat(row.dataset.lat || '0');
    var lng = parseFloat(row.dataset.lng || '0');
    return lat !== 0 && lng !== 0;
  }

  function sortByDistance() {
    if (!userLat || !userLng) return;

    rows.forEach(function (row) {
      var lat = parseFloat(row.dataset.lat || '0');
      var lng = parseFloat(row.dataset.lng || '0');
      row._distance = hasBoth(row) ? haversine(userLat, userLng, lat, lng) : Infinity;
    });

    var list = document.getElementById('venue-list');
    if (!list) return;
    var dividers = list.querySelectorAll('.section-divider');

    var openRows = rows.filter(function (r) { return r.dataset.closed !== 'true'; });
    var closedRows = rows.filter(function (r) { return r.dataset.closed === 'true'; });
    openRows.sort(function (a, b) { return a._distance - b._distance; });

    dividers.forEach(function (d) { d.style.display = 'none'; });
    openRows.forEach(function (r) { list.appendChild(r); });
    closedRows.forEach(function (r) { list.appendChild(r); });

    showDistanceBadges();
  }

  function showDistanceBadges() {
    rows.forEach(function (row) {
      var existing = row.querySelector('.distance-badge');
      if (existing) existing.remove();
      if (row._distance === undefined || row._distance === Infinity) return;
      var text = row._distance < 0.1 ? 'Here' : row._distance.toFixed(1) + ' mi';
      var badge = document.createElement('span');
      badge.className = 'badge badge-gray distance-badge';
      badge.textContent = text;
      var statusEl = row.querySelector('.venue-status');
      if (statusEl) statusEl.appendChild(badge);
    });
  }

  function requestLocation() {
    if (!navigator.geolocation) return;
    var btn = document.getElementById('near-me-btn');
    if (btn) { btn.textContent = 'Locating...'; btn.disabled = true; }

    navigator.geolocation.getCurrentPosition(
      function (pos) {
        userLat = pos.coords.latitude;
        userLng = pos.coords.longitude;
        if (btn) { btn.textContent = 'Nearest first'; btn.disabled = false; btn.classList.add('active'); }
        sortByDistance();
        if (mapInitialized) addUserMarker();
      },
      function () {
        if (btn) { btn.textContent = 'Near me'; btn.disabled = false; }
      }
    );
  }

  // === SHARE ===
  function shareVenue(btn, name) {
    var shareUrl = window.location.origin + window.location.pathname + '#' + slugify(name);
    if (navigator.share) {
      navigator.share({
        title: name + ' is free for Denver kids',
        text: 'Free admission for Denver kids: ' + name,
        url: shareUrl
      }).catch(function () {});
    } else if (navigator.clipboard) {
      navigator.clipboard.writeText(shareUrl).then(function () {
        var orig = btn.textContent;
        btn.textContent = 'Copied!';
        setTimeout(function () { btn.textContent = orig; }, 2000);
      }).catch(function () {});
    }
  }

  // === DIRECTIONS ===
  function getDirections(row) {
    var addr = row.dataset.address;
    if (!addr) return;
    window.open('https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(addr), '_blank', 'noopener,noreferrer');
  }

  // === WIRE UP ROW CLICKS ===
  rows.forEach(function (row) {
    row.addEventListener('click', function () { openModal(row); });
    row.addEventListener('keydown', function (e) {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        openModal(row);
      }
    });
  });

  // === AGE FILTER ===
  var kidAgeInput = document.getElementById('kid-age');
  if (kidAgeInput) {
    kidAgeInput.addEventListener('change', function () {
      kidAge = parseInt(this.value, 10) || 0;
      applyFilter();
    });
  }

  // === FILTER TABS ===
  function setTab(filter) {
    activeFilter = filter;
    tabs.forEach(function (t) { t.classList.toggle('active', t.dataset.filter === filter); });
  }

  tabs.forEach(function (tab) {
    tab.addEventListener('click', function () {
      setTab(tab.dataset.filter);
      applyFilter();
    });
  });

  // === TOOLBAR ===
  var nearMeBtn = document.getElementById('near-me-btn');
  if (nearMeBtn) nearMeBtn.addEventListener('click', requestLocation);

  var mapToggleBtn = document.getElementById('map-toggle-btn');
  if (mapToggleBtn) mapToggleBtn.addEventListener('click', toggleMap);

  // === INIT ===
  setTab('now');
  applyFilter();
  buildHero();

  // Deep link: auto-open modal if URL has a venue hash
  var initHash = window.location.hash.slice(1);
  if (initHash) {
    for (var i = 0; i < rows.length; i++) {
      if (slugify(rows[i].dataset.name || '') === initHash) {
        (function (r) { setTimeout(function () { openModal(r, true); }, 200); })(rows[i]);
        break;
      }
    }
  }
})();
</script>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
