// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/benhammondmusic/my-denver-card-free/internal/models"
	"strings"
)

var monthsFull = []string{
	"January", "February", "March", "April", "May", "June",
	"July", "August", "September", "October", "November", "December",
}

var monthsAbbr = []string{
	"Jan", "Feb", "Mar", "Apr", "May", "Jun",
	"Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
}

func freeMonthsLabel(v models.Venue) string {
	if len(v.FreeMonths) == 12 {
		return "Year-round"
	}
	return strings.Join(v.FreeMonths, ", ")
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func Index(venues []models.Venue) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"hero-section\"><p class=\"hero-eyebrow\">Free right now</p><div id=\"free-now-chips\" class=\"venue-chips\"></div><div id=\"hero-soon\"><div class=\"hero-divider\"></div><p class=\"hero-eyebrow soon\">Free next month</p><div id=\"free-soon-chips\" class=\"venue-chips\"></div></div></div><p class=\"browse-label\">Browse all venues</p><div class=\"filter-bar\"><div class=\"filter-tabs\"><button class=\"filter-tab\" data-filter=\"all\">All</button> <button class=\"filter-tab\" data-filter=\"now\">Free Now</button> <button class=\"filter-tab\" data-filter=\"weekend\">This Weekend</button> <button class=\"filter-tab\" data-filter=\"summer\">Summer</button> <button class=\"filter-tab\" data-filter=\"yearround\">Year-Round</button></div><div class=\"month-strip\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for i, abbr := range monthsAbbr {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button class=\"month-btn\" data-month-name=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(monthsFull[i])
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 55, Col: 62}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(abbr)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 55, Col: 71}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"toolbar\"><button class=\"toolbar-btn\" id=\"near-me-btn\">Near me</button> <button class=\"toolbar-btn\" id=\"map-toggle-btn\">Show map</button><div class=\"age-filter\"><label for=\"kid-age\">Age:</label> <input type=\"number\" id=\"kid-age\" class=\"age-input\" min=\"1\" max=\"18\" placeholder=\"any\"></div></div></div><div id=\"map-panel\" class=\"map-panel\"></div><p class=\"venue-count\"></p><ul class=\"venue-list\" id=\"venue-list\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, v := range venues {
				if v.Featured && !v.TemporarilyClosed {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<li class=\"section-divider\" aria-hidden=\"true\"><span>More venues</span></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, v := range venues {
				if !v.Featured && !v.TemporarilyClosed {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			for _, v := range venues {
				if v.TemporarilyClosed {
					templ_7745c5c3_Err = VenueRow(v).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = filterScript().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("My Denver Card Free: Denver Cultural Venues").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func VenueRow(v models.Venue) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var6 = []any{"venue-row", templ.KV("venue-featured", v.Featured), templ.KV("program-general", v.Program == models.ProgramGeneral), templ.KV("venue-closed", v.TemporarilyClosed)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var6...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<li class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var6).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" data-free-months=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(strings.Join(v.FreeMonths, ","))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 94, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" data-schedule=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(string(v.FreeSchedule))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 95, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" data-closed=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.TemporarilyClosed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 96, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" data-program=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.ResolveAttributeValue(string(v.Program))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 97, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" data-lat=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%.6f", v.Lat))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 98, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" data-lng=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%.6f", v.Lng))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 99, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" data-address=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.Address)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 100, Col: 26}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" data-indoor=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.Indoor))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 101, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\" data-reservation=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue(boolStr(v.ReservationRequired))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 102, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" data-min-age=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", v.MinAge))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 103, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\" data-max-age=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", v.MaxAge))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 104, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\"><div class=\"venue-band\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "<span class=\"band-label\">Closed</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if v.Program == models.ProgramGeneral {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<span class=\"band-label\">Free</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "<span class=\"band-label\">Card</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</div><div class=\"venue-body\"><div class=\"venue-name-row\"><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 templ.SafeURL
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(v.URL))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 117, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\" target=\"_blank\" rel=\"noopener noreferrer\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(v.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 117, Col: 87}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<span class=\"badge badge-red\">temporarily closed</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if v.ScrapeFailed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<span class=\"badge badge-red\" title=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var21 string
			templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.ResolveAttributeValue(v.ScrapeError)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 122, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var21)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\">data outdated</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if v.ReservationRequired {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<span class=\"badge badge-yellow\">reservation required</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if v.Indoor {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "<span class=\"badge badge-gray\">indoor</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "<p class=\"closure-reason\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var22 string
			templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(v.ClosureReason)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 132, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if v.Notes != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "<p class=\"venue-notes\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var23 string
			templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(v.Notes)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 134, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !v.TemporarilyClosed {
			if v.Hours != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "<p class=\"venue-hours\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var24 string
				templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(v.Hours)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 138, Col: 37}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, " <div class=\"venue-actions\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if v.Address != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "<button class=\"action-btn directions-btn\">Directions</button> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "<button class=\"action-btn share-btn\">Share</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !v.TemporarilyClosed {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "<div class=\"venue-status\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			switch {
			case v.AdultsIncluded >= 2:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "<span class=\"badge badge-green\">Whole family free</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case v.AdultsIncluded == 1:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "<span class=\"badge badge-green\">Free +1 adult</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			default:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "<span class=\"badge badge-yellow\">Kids free</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			switch v.FreeSchedule {
			case models.ScheduleWeekends:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "<span class=\"badge badge-gray\">Weekends only</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case models.ScheduleWeekendsAndBreaks:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, "<span class=\"badge badge-gray\">Weekends + breaks</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, "<span class=\"months\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var25 string
			templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(freeMonthsLabel(v))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 164, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "</li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func filterScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var26 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var26 == nil {
			templ_7745c5c3_Var26 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(`<script>
(function () {
  // === DATE / SCHEDULE CONSTANTS ===
  var MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  var today = new Date();
  var currentMonthName = MONTHS[today.getMonth()];
  var nextMonthName = MONTHS[(today.getMonth() + 1) % 12];
  var dow = today.getDay(); // 0=Sun 6=Sat
  var isWeekend = dow === 0 || dow === 5 || dow === 6; // Fri Sat Sun

  var weekendDates = (function () {
    var daysToFri = dow === 0 ? -2 : dow === 6 ? -1 : 5 - dow;
    return [0, 1, 2].map(function (i) {
      var d = new Date(today);
      d.setDate(today.getDate() + daysToFri + i);
      return d;
    });
  })();

  // School break approximation; update annually for DPS calendar
  function isSchoolBreak(d) {
    var m = d.getMonth(), day = d.getDate();
    if ((m === 11 && day >= 20) || (m === 0 && day <= 5)) return true; // Winter
    if (m === 2 && day >= 15 && day <= 29) return true;                 // Spring
    if (m >= 5 && m <= 7) return true;                                   // Summer Jun-Aug
    return false;
  }
  var inBreak = isSchoolBreak(today);

  // === STATE ===
  var activeFilter = 'now';
  var activeMonth = null;
  var kidAge = 0; // 0 = any age
  var userLat = null, userLng = null;
  var mapInitialized = false;
  var leafletMap = null;

  // === DOM REFS ===
  var rows = Array.prototype.slice.call(document.querySelectorAll('.venue-row'));
  var tabs = document.querySelectorAll('.filter-tab');
  var monthBtns = document.querySelectorAll('.month-btn');
  var countEl = document.querySelector('.venue-count');

  // === VENUE HELPERS ===
  function freeMonths(row) {
    return (row.dataset.freeMonths || '').split(',').filter(Boolean);
  }

  function freeNow(row) {
    if (row.dataset.closed === 'true') return false;
    if (freeMonths(row).indexOf(currentMonthName) === -1) return false;
    var sched = row.dataset.schedule || 'daily';
    if (sched === 'weekends') return isWeekend;
    if (sched === 'weekends_and_breaks') return isWeekend || inBreak;
    return true;
  }

  function freeThisWeekend(row) {
    if (row.dataset.closed === 'true') return false;
    var sched = row.dataset.schedule || 'daily';
    return weekendDates.some(function (d) {
      var monthName = MONTHS[d.getMonth()];
      if (freeMonths(row).indexOf(monthName) === -1) return false;
      return true;
    });
  }

  function freeInMonth(row, m) {
    return row.dataset.closed !== 'true' && freeMonths(row).indexOf(m) !== -1;
  }

  function isSummer(row) {
    if (row.dataset.closed === 'true') return false;
    var fm = freeMonths(row);
    return fm.indexOf('June') !== -1 || fm.indexOf('July') !== -1 || fm.indexOf('August') !== -1;
  }

  function isYearRound(row) {
    return row.dataset.closed !== 'true' && freeMonths(row).length === 12;
  }

  function passesAgeFilter(row) {
    if (kidAge === 0) return true;
    var minAge = parseInt(row.dataset.minAge || '0', 10);
    var maxAge = parseInt(row.dataset.maxAge || '0', 10);
    if (minAge > 0 && kidAge < minAge) return false;
    if (maxAge > 0 && kidAge > maxAge) return false;
    return true;
  }

  // === DISTANCE (Haversine, miles) ===
  function haversine(lat1, lng1, lat2, lng2) {
    var R = 3958.8;
    var dLat = (lat2 - lat1) * Math.PI / 180;
    var dLng = (lng2 - lng1) * Math.PI / 180;
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
            Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
            Math.sin(dLng/2) * Math.sin(dLng/2);
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  // === FILTER ===
  function _doApplyFilter() {
    var visible = 0;
    rows.forEach(function (row) {
      var closed = row.dataset.closed === 'true';
      var ageOk = closed || passesAgeFilter(row);
      var show;
      if (activeMonth) {
        show = closed || (freeInMonth(row, activeMonth) && ageOk);
      } else {
        switch (activeFilter) {
          case 'now':       show = closed || (freeNow(row) && ageOk);         break;
          case 'weekend':   show = closed || (freeThisWeekend(row) && ageOk); break;
          case 'summer':    show = closed || (isSummer(row) && ageOk);        break;
          case 'yearround': show = closed || (isYearRound(row) && ageOk);     break;
          default:          show = closed || ageOk;
        }
      }
      row.classList.toggle('hidden', !show);
      if (show && !closed) visible++;
    });

    var label = visible + (visible === 1 ? ' venue' : ' venues');
    if (activeMonth) {
      label += ' free in ' + activeMonth;
    } else if (activeFilter === 'now') {
      label += ' free today';
      if (visible === 0) label = 'No venues free right now. Try "All" or pick a month.';
    } else if (activeFilter === 'weekend') {
      label += ' free this weekend';
      if (visible === 0) label = 'Nothing free this weekend. Try "All" or pick a month.';
    }
    if (kidAge > 0) label += ' (age ' + kidAge + ')';
    if (countEl) countEl.textContent = label;
  }

  function applyFilter() {
    if (document.startViewTransition) {
      document.startViewTransition(_doApplyFilter);
    } else {
      _doApplyFilter();
    }
  }

  // === HERO ===
  function buildHero() {
    var nowChips = document.getElementById('free-now-chips');
    var soonChips = document.getElementById('free-soon-chips');
    var heroSoon = document.getElementById('hero-soon');
    var soonLabel = document.querySelector('.hero-eyebrow.soon');
    if (!nowChips || !soonChips) return;

    if (soonLabel) soonLabel.textContent = 'Coming up in ' + nextMonthName;

    var nowRows = rows.filter(function (row) { return freeNow(row); });
    var soonRows = rows.filter(function (row) {
      return !freeNow(row) && freeInMonth(row, nextMonthName) && row.dataset.closed !== 'true';
    });

    function makeName(row) {
      var a = row.querySelector('.venue-name-row a');
      return a ? a.textContent : '';
    }

    function makeChip(row, isSoon) {
      var btn = document.createElement('button');
      var cls = 'venue-chip';
      if (row.dataset.program === 'general') cls += ' general';
      if (isSoon) cls += ' chip-soon';
      btn.className = cls;
      btn.textContent = makeName(row);
      btn.addEventListener('click', function () {
        if (row.classList.contains('hidden')) {
          setTab('all');
          applyFilter();
        }
        row.scrollIntoView({ behavior: 'smooth', block: 'center' });
        row.classList.add('chip-highlight');
        setTimeout(function () { row.classList.remove('chip-highlight'); }, 1800);
      });
      return btn;
    }

    if (nowRows.length === 0) {
      var empty = document.createElement('span');
      empty.className = 'chip-empty';
      empty.textContent = 'Nothing is free right now. Pick a month below to plan ahead.';
      nowChips.appendChild(empty);
    } else {
      nowRows.forEach(function (row) { nowChips.appendChild(makeChip(row, false)); });
    }

    if (soonRows.length === 0) {
      if (heroSoon) heroSoon.style.display = 'none';
    } else {
      soonRows.forEach(function (row) { soonChips.appendChild(makeChip(row, true)); });
    }
  }

  // === MAP ===
  function initMap() {
    if (mapInitialized || typeof L === 'undefined') return;
    mapInitialized = true;

    leafletMap = L.map('map-panel').setView([39.7392, -104.9849], 12);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      maxZoom: 19
    }).addTo(leafletMap);

    rows.forEach(function (row) {
      var lat = parseFloat(row.dataset.lat || '0');
      var lng = parseFloat(row.dataset.lng || '0');
      if (!lat || !lng) return;

      var name = (row.querySelector('.venue-name-row a') || {}).textContent || '';
      var isFreeNow = freeNow(row);
      var isClosed = row.dataset.closed === 'true';
      var isGeneral = row.dataset.program === 'general';
      var color = isClosed ? '#6b7280' : (isFreeNow ? (isGeneral ? '#d97706' : '#002868') : '#93c5fd');

      var marker = L.circleMarker([lat, lng], {
        radius: 10,
        fillColor: color,
        color: 'white',
        weight: 2,
        opacity: 1,
        fillOpacity: 0.88
      });

      var statusHtml = isClosed
        ? '<span style="color:#991b1b">Temporarily closed</span>'
        : (isFreeNow
          ? '<span style="color:#065f46">Free now</span>'
          : '<span style="color:#6b7280">Not free this month</span>');
      marker.bindPopup('<strong>' + name + '</strong><br>' + statusHtml);

      marker.on('click', function () {
        if (row.classList.contains('hidden')) { setTab('all'); applyFilter(); }
        row.scrollIntoView({ behavior: 'smooth', block: 'center' });
        row.classList.add('chip-highlight');
        setTimeout(function () { row.classList.remove('chip-highlight'); }, 1800);
      });

      marker.addTo(leafletMap);
      row._marker = marker;
    });

    setTimeout(function () { if (leafletMap) leafletMap.invalidateSize(); }, 100);
  }

  function toggleMap() {
    var panel = document.getElementById('map-panel');
    var btn = document.getElementById('map-toggle-btn');
    if (!panel) return;
    var isVisible = panel.classList.contains('visible');
    panel.classList.toggle('visible', !isVisible);
    if (btn) btn.textContent = isVisible ? 'Show map' : 'Hide map';
    if (btn) btn.classList.toggle('active', !isVisible);
    if (!isVisible) {
      initMap();
      setTimeout(function () { if (leafletMap) leafletMap.invalidateSize(); }, 150);
    }
  }

  // === GEOLOCATION / NEAR ME ===
  function hasBoth(row) {
    var lat = parseFloat(row.dataset.lat || '0');
    var lng = parseFloat(row.dataset.lng || '0');
    return lat !== 0 && lng !== 0;
  }

  function sortByDistance() {
    if (!userLat || !userLng) return;

    rows.forEach(function (row) {
      var lat = parseFloat(row.dataset.lat || '0');
      var lng = parseFloat(row.dataset.lng || '0');
      row._distance = hasBoth(row) ? haversine(userLat, userLng, lat, lng) : Infinity;
    });

    var list = document.getElementById('venue-list');
    if (!list) return;
    var divider = list.querySelector('.section-divider');

    var openRows = rows.filter(function (r) { return r.dataset.closed !== 'true'; });
    var closedRows = rows.filter(function (r) { return r.dataset.closed === 'true'; });
    openRows.sort(function (a, b) { return a._distance - b._distance; });

    if (divider) divider.style.display = 'none';
    openRows.forEach(function (r) { list.appendChild(r); });
    closedRows.forEach(function (r) { list.appendChild(r); });

    showDistanceBadges();
  }

  function showDistanceBadges() {
    rows.forEach(function (row) {
      var existing = row.querySelector('.distance-badge');
      if (existing) existing.remove();
      if (row._distance === undefined || row._distance === Infinity) return;
      var text = row._distance < 0.1 ? 'Here' : row._distance.toFixed(1) + ' mi';
      var badge = document.createElement('span');
      badge.className = 'badge badge-gray distance-badge';
      badge.textContent = text;
      var statusEl = row.querySelector('.venue-status');
      if (statusEl) statusEl.appendChild(badge);
    });
  }

  function addUserMarker() {
    if (!leafletMap || !userLat || !userLng) return;
    L.circleMarker([userLat, userLng], {
      radius: 8,
      fillColor: '#bf0a30',
      color: 'white',
      weight: 2,
      fillOpacity: 0.9
    }).bindPopup('You are here').addTo(leafletMap);
    leafletMap.setView([userLat, userLng], 13);
  }

  function requestLocation() {
    if (!navigator.geolocation) return;
    var btn = document.getElementById('near-me-btn');
    if (btn) { btn.textContent = 'Locating...'; btn.disabled = true; }

    navigator.geolocation.getCurrentPosition(
      function (pos) {
        userLat = pos.coords.latitude;
        userLng = pos.coords.longitude;
        if (btn) { btn.textContent = 'Near me'; btn.disabled = false; btn.classList.add('active'); }
        sortByDistance();
        if (mapInitialized) addUserMarker();
      },
      function () {
        if (btn) { btn.textContent = 'Near me'; btn.disabled = false; }
      }
    );
  }

  // === SHARE ===
  function shareVenue(btn, row) {
    var a = row.querySelector('.venue-name-row a');
    var name = a ? a.textContent.trim() : 'Denver venue';
    var url = a ? a.href : window.location.href;
    if (navigator.share) {
      navigator.share({
        title: name + ' is free for Denver kids',
        text: 'Free admission for Denver kids: ' + name,
        url: url
      }).catch(function () {});
    } else if (navigator.clipboard) {
      navigator.clipboard.writeText(url).then(function () {
        var orig = btn.textContent;
        btn.textContent = 'Copied!';
        setTimeout(function () { btn.textContent = orig; }, 2000);
      }).catch(function () {});
    }
  }

  // === DIRECTIONS ===
  function getDirections(row) {
    var addr = row.dataset.address;
    if (!addr) return;
    window.open('https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(addr), '_blank', 'noopener,noreferrer');
  }

  // === AGE FILTER ===
  var kidAgeInput = document.getElementById('kid-age');
  if (kidAgeInput) {
    kidAgeInput.addEventListener('input', function () {
      kidAge = parseInt(this.value, 10) || 0;
      applyFilter();
    });
  }

  // === WIRE UP ACTION BUTTONS ===
  rows.forEach(function (row) {
    var dirBtn = row.querySelector('.directions-btn');
    if (dirBtn) dirBtn.addEventListener('click', function () { getDirections(row); });

    var shareBtn = row.querySelector('.share-btn');
    if (shareBtn) shareBtn.addEventListener('click', function () { shareVenue(shareBtn, row); });
  });

  // === MONTH STRIP ===
  monthBtns.forEach(function (btn) {
    if (btn.dataset.monthName === currentMonthName) btn.classList.add('current-month');
    btn.addEventListener('click', function () {
      if (activeMonth === btn.dataset.monthName) {
        activeMonth = null;
        btn.classList.remove('active');
        setTab('now');
      } else {
        activeMonth = btn.dataset.monthName;
        monthBtns.forEach(function (b) { b.classList.remove('active'); });
        btn.classList.add('active');
        tabs.forEach(function (t) { t.classList.remove('active'); });
      }
      applyFilter();
    });
  });

  // === FILTER TABS ===
  function setTab(filter) {
    activeFilter = filter;
    activeMonth = null;
    monthBtns.forEach(function (b) { b.classList.remove('active'); });
    tabs.forEach(function (t) { t.classList.toggle('active', t.dataset.filter === filter); });
  }

  tabs.forEach(function (tab) {
    tab.addEventListener('click', function () {
      setTab(tab.dataset.filter);
      applyFilter();
    });
  });

  // === TOOLBAR BUTTONS ===
  var nearMeBtn = document.getElementById('near-me-btn');
  if (nearMeBtn) nearMeBtn.addEventListener('click', requestLocation);

  var mapToggleBtn = document.getElementById('map-toggle-btn');
  if (mapToggleBtn) mapToggleBtn.addEventListener('click', toggleMap);

  // === INIT ===
  setTab('now');
  applyFilter();
  buildHero();
})();
</script>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
